##   Copyright (c) Aslak W. Bergersen, Henrik A. Kjeldsberg. All rights reserved.
##   See LICENSE file for details.

##      This software is distributed WITHOUT ANY WARRANTY; without even
##      the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
##      PURPOSE.  See the above copyright notices for more information.

notifications:
  - provider: Email
    to:
      - henrik.kjeldsberg@live.no
    on_build_success: true

environment:
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script interpreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\continuous-integration\\appveyor\\run_with_env.cmd"

  matrix:
    - PYTHON: "C:\\Python35_64"
      PYTHON_VERSION: "3.5"
      PYTHON_ARCH: "64"
      CONDA_PY: "35"
      CONDA_NPY: "18"
      APP_CONDA_PY: "3.5.1"

    - PYTHON: "C:\\Python36_64"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "64"
      CONDA_PY: "36"
      CONDA_NPY: "18"
      APP_CONDA_PY: "3.6.1"

platform:
  - x64

configuration:
  - Release

install:
  # Installs the appropriate Miniconda (Py2/Py3, 32/64 bit),
  - powershell .\\continuous-integration\\appveyor\\install.ps1
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"

  # Conda setup
  #- "%CMD_IN_ENV% conda config --add channels vmtk"
  #- "%CMD_IN_ENV% conda config --add channels morphman"
  #- "%CMD_IN_ENV% conda config --set always_yes yes"

  # Useful for debugging any issues with conda
  #- "%CMD_IN_ENV% conda info -a"

  # Update conda
  #- "%CMD_IN_ENV% conda update -q conda"

  # Create environment for morphman
  #- "%CMD_IN_ENV% conda create -n morphman python=%PYTHON_VERSION% morphman vmtk"

  # Activate environment
  #- activate morphman

  # Install morphman
  #- conda install pytest

  # Search and replace in vmtkcenterlines.py for / to //
  #- sed -i 's/len(self.SourcePoints)\/3/len\(self.SourcePoints\)\/\/3/g' ..\\..\\Python36_64\\envs\\morphman_env\\lib\\site-packages\\vmtk\\vmtkcenterlines.py
  #- sed -i 's/len(self.TargetPoints)\/3/len\(self.TargetPoints\)\/\/3/g' ..\\..\\Python36_64\\envs\\morphman_env\\lib\\site-packages\\vmtk\\vmtkcenterlines.py

  # Workaround for downloading on windows, as bitsadmin is not in sync on AppVeyor
  #- cd .\\test
  #- ps: Start-FileDownload 'http://ecm2.mathcs.emory.edu/aneuriskdata/download/C0001/C0001_models.tar.gz'
  #- tar --force-local -zxvf C0001_models.tar.gz
  #- del /f C0001_models.tar.gz
  #- cd ..
  
#build_script:
  # Build the compiled extension
  # - "%CMD_IN_ENV% python setup.py build"

build: false

test_script:
  - dir
  - cd\
  - cd .\\projects\\morphman-s1s38\\test
  - dir
  - ps: Start-FileDownload 'http://ecm2.mathcs.emory.edu/aneuriskdata/download/C0001/C0001_models.tar.gz'
  - tar --force-local -zxvf C0001_models.tar.gz
  - del /f C0001_models.tar.gz
  - cd\
  - dir
  
  # Search and replace in vmtkcenterlines.py for / to //
  - sed -i 's/len(self.SourcePoints)\/3/len\(self.SourcePoints\)\/\/3/g' .\\Python%CONDA_PY%_64\lib\site-packages\vmtk\vmtkcenterlines.py
  - sed -i 's/len(self.TargetPoints)\/3/len\(self.TargetPoints\)\/\/3/g' .\\Python%CONDA_PY%_64\lib\site-packages\vmtk\vmtkcenterlines.py
  
  - "%CMD_IN_ENV% conda update -q conda"
  - "%CMD_IN_ENV% conda config --set always_yes yes"
  - "%CMD_IN_ENV% conda config --add channels vmtk"
  - "%CMD_IN_ENV% conda config --add channels morphman"
  - "%CMD_IN_ENV% conda config --show"
  - "%CMD_IN_ENV% conda install pytest vtk vmtk scipy numpy"
  - "%CMD_IN_ENV% conda build --python %APP_CONDA_PY% ."
  - "%CMD_IN_ENV% cd .\\test"
  - "%CMD_IN_ENV% pytest ."
