package:
  name: morphman
  version: "0.1"

source:
  git_rev: v0.1
  path: ../

build:
  number: 1
  script: python setup.py install

requirements:
  build:
    - python
    - setuptools

  run:
    - python {{ python }}
    - setuptools
    - scipy >=1.0.0
    - numpy >=1.13
    - vtk {{ vtk }}
    - vmtk

test:
  imports:
    - morphman
  source_files:
    - ./test
  requires:
    - pytest


about:
  home: https://github.com/KVSlab/morphMan
  summary: 'morphMan - morphological manipulation'
  license: GNU GPL 3.0
  license_file: LICENSE
  doc_url: https://morphman.readthedocs.io
